// demo-animation/src/App.tsx
import React from "react";
import { Route, Routes, useNavigate } from "react-router-dom";
import "./App.css";
import { Layout, Menu, MenuProps } from "antd";
import "animate.css";

const { Sider, Content } = Layout;
// @ts-ignore
const modulesFiles = require.context("./pages", true, /index.tsx/);

const menus: any = {};
const routes: any[] = [];

modulesFiles
  .keys()
  // .sort((a: string, b: string) => a.length - b.length)
  .forEach((path: string) => {
    const pathName = path.slice(2, path.length - 10);
    const pathNameArr: any[] = pathName.split("/");
    if (pathNameArr.length === 1) {
      // 无子菜单
      menus[pathNameArr[0]] = true;
      const name = pathNameArr[0];
      routes.push({
        path: name === "home" ? "/" : `/${name}`,
        component: modulesFiles(path).default,
      });
    } else {
      // 有子菜单
      if (!Object.prototype.hasOwnProperty.call(menus, pathNameArr[0])) {
        menus[pathNameArr[0]] = {
          children: [],
        };
      }
      menus[pathNameArr[0]].children.push({
        name: pathNameArr[1],
        // component:
      });
      routes.push({
        path: `/${pathNameArr[0]}/${pathNameArr[1]}`,
        component: modulesFiles(path).default,
      });
    }
  });

const items: MenuProps["items"] = Object.keys(menus).map((menuName: string) => {
  if (menus[menuName].children) {
    /* return (
      <SubMenu key={menuName} title={menuName}>
        {menus[menuName].children.map(({ name }: any) => {
          return <Menu.Item key={name}>{name}</Menu.Item>;
        })}
      </SubMenu>
    ); */
    return {
      key: menuName,
      label: menuName,
      children: menus[menuName].children.map(({ name }: any) => {
        // return <Menu.Item key={name}>{name}</Menu.Item>;
        return {
          key: name,
          label: name,
        };
      }),
    };
  } else
    return {
      key: menuName,
      label: menuName,
    };
});

function App() {
  const navigate = useNavigate();

  const jumpTo = ({ item, key, keyPath, domEvent }: any) => {
    if (key === "home") {
      navigate("/");
    } else {
      const path = keyPath.reverse().join("/");
      navigate(path);
    }
  };

  return (
    <Layout className="h-screen">
      <Sider>
        <Menu theme="dark" mode="inline" items={items} onClick={jumpTo} />
      </Sider>
      <Layout className="site-layout">
        <Content className="h-screen">
          <Routes>
            {routes.map((route) => (
              <Route
                key={route.path}
                path={route.path}
                element={<route.component />}
              ></Route>
            ))}
          </Routes>
        </Content>
      </Layout>
    </Layout>
  );
}

export default App;

// demo-antdv/src/App.vue
<template>
  <a-layout class="wh100">
    <a-layout-sider>
      <a-menu theme="dark" mode="inline" @click="jumpTo">
        <template v-for="menuKey of Object.keys(menus)">
          <a-menu-item v-if="!menus[menuKey].children" :key="`${menuKey}`">
            <span>{{ menuKey }}</span>
          </a-menu-item>
          <a-sub-menu :key="menuKey" v-else>
            <template #title>
              <span>
                <span>{{ menuKey }}</span>
              </span>
            </template>
            <a-menu-item
              v-for="menuName in menus[menuKey].children"
              :key="menuName.name"
              >{{ menuName.name }}</a-menu-item
            >
          </a-sub-menu>
        </template>
      </a-menu>
    </a-layout-sider>
    <a-layout>
      <router-view></router-view>
    </a-layout>
  </a-layout>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { menus, base } from "./data/viewsData";

export default defineComponent({
  name: "App",
  data() {
    return {
      menus: menus,
    };
  },
  methods: {
    jumpTo({ item, key, keyPath }: any) {
      if (key === "home") {
        this.$router.push(`${base}/`);
      } else {
        const path = keyPath.join("/");
        this.$router.push(`${base}/${path}`);
      }
    },
  },
});
</script>

<style lang="less"></style>
